# Generated by Django 3.0.6 on 2020-06-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='description',
            field=models.TextField(default='class description', max_length=250),
        ),
        migrations.AlterField(
            model_name='classes',
            name='date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='classes',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
