# Generated by Django 3.0.6 on 2020-06-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0009_auto_20200614_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='classes',
            field=models.ManyToManyField(to='gym.Classes'),
        ),
    ]
