# Generated by Django 3.0.6 on 2020-06-25 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0010_profile_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='limit',
            field=models.PositiveIntegerField(default=15, null=True),
        ),
        migrations.AlterField(
            model_name='classes',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(choices=[(1, 'Bad trainer'), (2, 'Not good trainer'), (3, 'Not bad trainer'), (4, 'Good trainer'), (5, 'Very good trainer')])),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.Trainer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.Profile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='rate',
            constraint=models.UniqueConstraint(fields=('trainer', 'user'), name='one_time_rating_trainer'),
        ),
    ]
