# Generated by Django 3.0.6 on 2020-06-30 18:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gym', '0012_remove_classes_is_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='rate',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
