# Generated by Django 3.0.6 on 2020-06-30 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0013_classes_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='rate',
        ),
        migrations.AddField(
            model_name='rate',
            name='classes',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gym.Classes'),
            preserve_default=False,
        ),
    ]
