# Generated by Django 3.0.6 on 2020-06-30 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0014_auto_20200630_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='classes',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gym.Classes'),
        ),
    ]
