# Generated by Django 3.0.6 on 2020-06-30 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0016_auto_20200630_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='classes',
            new_name='clss',
        ),
    ]
