# Generated by Django 3.0.6 on 2020-06-30 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0019_auto_20200630_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='class_id',
        ),
    ]
