# Generated by Django 3.0.6 on 2020-06-30 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0020_remove_rate_class_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='class_id',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='gym.Classes'),
            preserve_default=False,
        ),
    ]
