# Generated by Django 3.0.6 on 2020-06-30 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0021_rate_class_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='class_id',
            new_name='classes',
        ),
    ]
