# Generated by Django 3.0.6 on 2020-06-30 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0022_auto_20200630_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.IntegerField(choices=[(1, 'Very bad'), (2, 'Bad'), (3, 'Mediocre'), (4, 'Good'), (5, 'Very good')]),
        ),
    ]
