# Generated by Django 3.0.6 on 2020-07-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0023_auto_20200630_2300'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rate',
            name='one_time_rating_trainer',
        ),
        migrations.AddConstraint(
            model_name='rate',
            constraint=models.UniqueConstraint(fields=('classes', 'user'), name='one_time_rating_classes'),
        ),
    ]
